Add checkout command

diff --git a/git-mrepo b/git-mrepo
--- a/git-mrepo
+++ b/git-mrepo
@@ -9,14 +9,14 @@ MAX_REPO_DIR_LENGTH=24
 # Default number of how many commits do we want to display per repository
 # This can be adjusted for required commands
 NUMBER_OF_COMMITS=5
- 
+
 # Associative arrays containing info for projects and colors
 declare -A projects
 declare -A pcolors
 
 usage() {
 
-cat <<EOS
+	cat <<EOS
     GIT Multi Repository Tooling
 
     usage: repo [[status] | [pull] | [branch [0 1 2]] | [log] | [dirty] | [help] | [repos] | checkout [<branch>]]
@@ -52,325 +52,361 @@ EOS
 
 # Error handling funcion
 failAndExit() {
-    echo "Error occured >> $1"
-    exit
+	echo -e "[\e[1;91m ERROR \e[0m] $1\e[0m"
+	exit
 }
 
 repo_pull() {
-    local gitdata=$(git pull)
-    _r_decorate "$gitdata"   
+	local gitdata=$(git pull)
+	_r_decorate "$gitdata"
 }
 
 repo_fetch() {
-    local gitdata=$(git fetch)
-    _r_decorate "$gitdata"   
+	local gitdata=$(git fetch)
+	_r_decorate "$gitdata"
 }
 
 repo_diff() {
-    local gitdata=$(git diff origin/master --color=always)
-    _r_decorate "$gitdata"   
+	local gitdata=$(git diff origin/master --color=always)
+	_r_decorate "$gitdata"
 }
 
-# Get current repository directory name and trim it to 
-_r_dir() {    
-    printf "%s" "${PWD##*/}" | cut -c1-$MAX_REPO_DIR_LENGTH
+# Get current repository directory name and trim it to
+_r_dir() {
+	printf "%s" "${PWD##*/}" | cut -c1-$MAX_REPO_DIR_LENGTH
 }
 
 ## Decorate passed in lines with the current repo directory
-_r_decorate() {   
-   local blue=$(tput setaf 4)
-   local green=$(tput setaf 2)
-   local normal=$(tput sgr0)   
+_r_decorate() {
+	local blue=$(tput setaf 4)
+	local green=$(tput setaf 2)
+	local normal=$(tput sgr0)
 
-   local dir="$(_r_dir)"
-   
-   if [ -z "${1}" ]; then
-     return
-   fi
+	local dir="$(_r_dir)"
 
-   IFS=$'\n'
-   while read -r line
-   do      
-      local current=$(echo -e "${PWD}")      
-      local randomcolor=$(tput setaf ${pcolors[$current]})
-      # Remove leading whitespace from, git is reporting ' M ' with leading space white 'A' or '??' does not
-      local clean="$(echo -e "$line" | sed -e 's/^[[:space:]]*//')"      
-      printf "${randomcolor}%-24s| ${normal}%s\n" "$dir" "$clean"
-   done <<< "${1}"
+	if [ -z "${1}" ]; then
+		return
+	fi
+
+	IFS=$'\n'
+	while read -r line; do
+		local current=$(echo -e "${PWD}")
+		local randomcolor=$(tput setaf ${pcolors[$current]})
+		# Remove leading whitespace from, git is reporting ' M ' with leading space white 'A' or '??' does not
+		local clean="$(echo -e "$line" | sed -e 's/^[[:space:]]*//')"
+		printf "${randomcolor}%-24s| ${normal}%s\n" "$dir" "$clean"
+	done <<<"${1}"
 }
 
 repo_status() {
-    # default to show status in short version
-    local gitstat=$(git -c color.status=always status -s)
-    _r_decorate "$gitstat"
+	# default to show status in short version
+	local gitstat=$(git -c color.status=always status -s)
+	_r_decorate "$gitstat"
 }
 
-repo_log() {    
-    #git log --all --pretty=format:"- %s [%h] (%ae; %ar)"
-    # Add  -p to display line by line changes
-    # Add --since='9am yesterday'
-    # Add --author=$USER
-    #local gitlog=$(git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit)
-    local gitlog=$(git log -n $NUMBER_OF_COMMITS --pretty=format:'%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%Creset %C(yellow)%d%Creset' --abbrev-commit)
-    _r_decorate "$gitlog"
+repo_log() {
+	#git log --all --pretty=format:"- %s [%h] (%ae; %ar)"
+	# Add  -p to display line by line changes
+	# Add --since='9am yesterday'
+	# Add --author=$USER
+	#local gitlog=$(git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit)
+	local gitlog=$(git log -n $NUMBER_OF_COMMITS --pretty=format:'%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%Creset %C(yellow)%d%Creset' --abbrev-commit)
+	_r_decorate "$gitlog"
 }
 
-repo_stanup() {    
-    # Add  -p to display line by line changes
-    # Add --since='9am yesterday'
-    # Add --author=$USER    
-    local payload=$(git log --pretty=format:'%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%Creset %C(yellow)%d%Creset' --abbrev-commit --since='9am yesterday' -p) 
-    _r_decorate "$payload"
+repo_stanup() {
+	# Add  -p to display line by line changes
+	# Add --since='9am yesterday'
+	# Add --author=$USER
+	local payload=$(git log --pretty=format:'%Cred%h%Creset - %s %Cgreen(%cr) %C(bold blue)<%an>%Creset %C(yellow)%d%Creset' --abbrev-commit --since='9am yesterday' -p)
+	_r_decorate "$payload"
 }
 
 repo_branch() {
-    local gcmd="";
-    if [ "$cmd_branch_extended" = "1" ]; then
-	  gcmd=$(git ls-remote  origin)  # This will display both tags and  branches, for branches only use :  git ls-remote --heads origin
-    elif [ "$cmd_branch_extended" = "2" ]; then
-      gcmd=$(git remote show origin)
-    else
-        # gcmd=$(git branch -r --color=always)
-        gcmd=$(git branch -r | cut -d' ' -f3 | xargs git show --pretty='%Cgreen%ai %Creset%h  %an %d' -s | sed '/^$/d' | sort | uniq)        
-    fi
+	local gcmd=""
+	if [ "$cmd_branch_extended" = "1" ]; then
+		gcmd=$(git ls-remote origin) # This will display both tags and  branches, for branches only use :  git ls-remote --heads origin
+	elif [ "$cmd_branch_extended" = "2" ]; then
+		gcmd=$(git remote show origin)
+	else
+		# gcmd=$(git branch -r --color=always)
+		gcmd=$(git branch -r | cut -d' ' -f3 | xargs git show --pretty='%Cgreen%ai %Creset%h  %an %d' -s | sed '/^$/d' | sort | uniq)
+	fi
 
-    _r_decorate "$gcmd"
+	_r_decorate "$gcmd"
 }
 
 repo_dirty() {
-    # list all the files in the repo, including staged one but not yet commited
-    local info=$(git ls-files -m) # Modified
-   # git diff-index --cached HEAD # Uncommitted
+	# list all the files in the repo, including staged one but not yet commited
+	local info=$(git ls-files -m) # Modified
+	# git diff-index --cached HEAD # Uncommitted
 }
 
 quiet_git() {
-    stdout=$(tempfile)
-    stderr=$(tempfile)
+	stdout=$(tempfile)
+	stderr=$(tempfile)
 
-    if ! git "$@" </dev/null >$stdout 2>$stderr; then
-        cat $stderr >&2
-        rm -f $stdout $stderr
-        exit 1
-    fi
-    rm -f $stdout $stderr
+	if ! git "$@" </dev/null >$stdout 2>$stderr; then
+		cat $stderr >&2
+		rm -f $stdout $stderr
+		exit 1
+	fi
+	cat $stdout
+	rm -f $stdout $stderr
 }
 
 repo_checkout() {
-    local p1=$2
-    local b2c=""
+	local p1=$2
+	local b2c=""
 
-    if [ "$p1" = "-b" ]; then
-        b2c=$3
-    else
-        b2c=$2
-    fi
+	if [ "$p1" = "-b" ]; then
+		b2c=$3
+	else
+		b2c=$2
+	fi
 
-   echo -e "[\e[1;93m INFO  \e[0m] Preflight check, checkout (\e[1;92m$b2c\e[0m)"    
+	if [ "$b2c" = "" ]; then
+		failAndExit "Empty branch name is not allowed"
+	fi
 
-   issues=0
-   hasErrors=0
-   firstBranch=""
-   for projectdir in "${projects[@]}"; do     
-       # resolve symlinks
-       if [[ -d "$projectdir" && ! -L "$projectdir" ]]; then  
-           cd "$projectdir" || failAndExit "change directory : $projectdir"
-           project=${PWD##*/}
-           # read and parse, there will alwyas be a branch at index 0                    
-           msg=$(git status --branch --porcelain)
-           while read -r line; do array+=("$line"); done <<< "$msg"
-           branch=${array[0]}
-           #cleanup string : ex ' ## master'
-           branch="${branch// /}"
-           branch="${branch//#/}"
+	blanks=$(printf "%-14s" "") # pad with blanks
+	echo -e "[\e[1;93m INFO  \e[0m] [$blanks] Preflight check"
+	echo -e "[\e[1;93m INFO  \e[0m] [$blanks] Checkout branch : '\e[1;92m$b2c\e[0m'"
 
-           if [ "$firstBranch" == "" ]; then
-            firstBranch=$branch
-           fi
+	issues=0
+	hasErrors=0
+	firstBranch=""
+	for projectdir in "${projects[@]}"; do
+		# resolve symlinks
+		if [[ -d "$projectdir" && ! -L "$projectdir" ]]; then
+			cd "$projectdir" || failAndExit "change directory : $projectdir"
+			project=${PWD##*/}
+			trimmed=$(echo "$project" | cut -c1-$MAX_REPO_DIR_LENGTH) #
+			trimmed=$(printf "%-12s" $trimmed)                        # pad
 
-           if [ ${#array[@]} -gt 1 ]; then
-            hasErrors=1
-            ((issues++))
-            echo -e "[\e[1;91m ERROR \e[0m] $project (\e[1;92m$branch\e[0m)"                     
-            for element in "${array[@]}"
-            do
-                echo -e "[\e[1;91m  ---  \e[0m] $element"
-            done
+			# read and parse, there will alwyas be a branch at index 0
+			## this will be of format '## branchname'
+			#msg=$(git status --branch --porcelain)
+			msg=$(git branch -a | grep '*' | cut -d' ' -f2)
 
-           elif [ "$branch" != "$firstBranch" ]; then                         
-             ((issues++))
-             # no header present add one
-             if [ $hasErrors == 0 ]; then
-                echo -e "[\e[1;91m ERROR \e[0m] $project (\e[1;92m$branch\e[0m)"                     
-             fi
-             echo -e "[\e[1;91m  ---  \e[0m] Branch missmatch(\e[1;91m$firstBranch\e[0m != \e[1;92m$branch\e[0m)"           
-             hasErrors=1
-           else
-             echo -e "[\e[1;92m OK    \e[0m] $project (\e[1;92m$branch\e[0m)"    
-           fi
-           unset array
-        fi; 
-    done  
+			while read -r line; do array+=("$line"); done <<<"$msg"
+			branch=${array[0]}
+			#cleanup string : ex ' ## master'
+			branch="${branch// /}"
+			branch="${branch//#/}"
 
-    if [ $hasErrors == 1 ]; then
-      echo -e "[\e[1;91m ERROR \e[0m] Preflight failed, Please Fix All Issues Before Continuing : $issues"    
-      exit 1
-    fi
-    
-    echo -e "[\e[1;93m INFO  \e[0m] Preflight complete" 
-    echo -e "[\e[1;93m INFO  \e[0m] Checking out projects"
+			if [ "$firstBranch" == "" ]; then
+				firstBranch=$branch
+			fi
 
-    for projectdir in "${projects[@]}"; do     
-       # resolve symlinks
-       if [[ -d "$projectdir" && ! -L "$projectdir" ]]; then  
-           cd "$projectdir" || failAndExit "change directory : $projectdir"
-           project=${PWD##*/}    
-           echo -e "[\e[1;93m INFO \e[0m] (\e[1;92m$project\e[0m)"               
-           if [ "$p1" = "-b" ]; then
-               git checkout -b "$b2c"
-                #--quiet &> /dev/null
-           else
-               git checkout "$b2c" #--quiet &> /dev/null
-           fi
+			if [ ${#array[@]} -gt 1 ]; then
+				hasErrors=1
+				((issues++))
+				echo -e "[\e[1;91m ERROR \e[0m] [ $trimmed ] (\e[1;92m$branch\e[0m)"
+				for element in "${array[@]}"; do
+					echo -e "[\e[1;91m  ---  \e[0m] $element"
+				done
 
-           if [ $? = 0 ]; then
-            echo -e "[\e[1;92m OK    \e[0m] Checkout complete" 
-           else
-            echo -e "[\e[1;91m ERROR \e[0m] Checkout failed"
-           fi
-        fi; 
-    done  
+			elif [ "$branch" != "$firstBranch" ]; then
+				((issues++))
+				# no header present add one
+				if [ $hasErrors == 0 ]; then
+					echo -e "[\e[1;91m ERROR \e[0m] [ $trimmed ] On branch : '\e[1;92m$branch\e[0m'"
+				fi
+				echo -e "[\e[1;91m  ---  \e[0m] [ $trimmed ] Branch missmatch(\e[1;91m$firstBranch\e[0m != \e[1;92m$branch\e[0m)"
+				hasErrors=1
+			else
+				echo -e "[\e[1;92m OK    \e[0m] [ $trimmed ] On branch : '\e[1;92m$branch\e[0m'"
+			fi
+			unset array
+		fi
+	done
+
+	if [ $hasErrors == 1 ]; then
+		echo -e "[\e[1;91m ERROR \e[0m] [$blanks] Preflight failed, Please Fix All Issues Before Continuing : $issues"
+		exit 1
+	fi
+
+	echo -e "[\e[1;93m INFO  \e[0m] [$blanks] Preflight complete"
+	echo -e "[\e[1;93m INFO  \e[0m] [$blanks] Checking out projects"
+
+	for projectdir in "${projects[@]}"; do
+		# resolve symlinks
+		if [[ -d "$projectdir" && ! -L "$projectdir" ]]; then
+			cd "$projectdir" || failAndExit "change directory : $projectdir"
+			project=${PWD##*/}
+			trimmed=$(echo "$project" | cut -c1-$MAX_REPO_DIR_LENGTH) #
+			trimmed=$(printf "%-12s" $trimmed)                        # pad
+
+			stdout=$(tempfile)
+			if [ "$p1" = "-b" ]; then
+				# check if the branch exists to prevent "fatal: A branch named 'XYZ' already exists"
+				git show-ref --heads --quiet "$b2c"
+				# $? == 0 means local branch exists
+				if [ "$?" = 0 ]; then
+					msg=$(git checkout "$b2c" >$stdout 2>&1)
+				else
+					msg=$(git checkout -b "$b2c" >$stdout 2>&1)
+				fi
+			else
+				msg=$(git checkout "$b2c" --quiet >$stdout 2>&1)
+			fi
+			msg=$(cat $stdout)
+			rm -f $stdout
+
+			if [ $? = 0 ]; then
+				echo -e "[\e[1;92m OK    \e[0m] [ $trimmed ] $msg"
+				#echo -e "[\e[1;92m OK    \e[0m] Checkout status : $msg"
+			else
+				echo -e "[\e[1;91m ERROR \e[0m] Checkout failed"
+			fi
+		fi
+	done
 }
 
 dir_resolve() {
-  cd "$1" 2>/dev/null || return $?  # cd to desired directory; if fail, quell any error messages but return exit status
-  echo "`pwd -P`" # output full, link-resolved path
+	cd "$1" 2>/dev/null || return $? # cd to desired directory; if fail, quell any error messages but return exit status
+	echo "$(pwd -P)"                 # output full, link-resolved path
 }
 
 # Display one line repo information
 repo_repos() {
-     # local info=$(git show --summary --oneline --color=always)    
-    local branch="$(git symbolic-ref --short HEAD)"
-    local property="branch.${branch}.description"
-    local info=$(git config --get "$property")
+	# local info=$(git show --summary --oneline --color=always)
+	local branch="$(git symbolic-ref --short HEAD)"
+	local property="branch.${branch}.description"
+	local info=$(git config --get "$property")
 
-    if [ "$branch" != "master" ]; then
-        branch="\e[91m$branch";
-    fi
+	if [ "$branch" != "master" ]; then
+		branch="\e[91m$branch"
+	fi
 
-    _r_decorate "$branch $info"
+	_r_decorate "$branch $info"
 }
 
 if [ $# -eq 0 ]; then
-   usage
-   exit 1
+	usage
+	exit 1
 fi
 
 # Collect parameters
 while [ "$1" != "" ]; do
-    case $1 in
-        -r | repos )            cmd='repos'
-                                ;;
-        -p | pull )             cmd='pull'
-                                ;;
-        -up | standup)          cmd='standup'
-                                # consume arguments
-                                while [ "$1" != "" ]; do
-                                     echo "param : $1"
-                                    #case $1 in
-                                    #esac
-                                shift   
-                                done
-                                ;;
-        -s | status )           cmd='status'
-                                ;;
-        -f | fetch )            cmd='fetch'
-                                ;;                                
-        -df | diff )            cmd='diff'
-                                ;;                       
-        -b | branch )           
-                                cmd='branch'
-                                shift
-                                cmd_branch_extended=$1
-                                ;;
-        -l | log )              cmd='log'
-                                ;;
-        -d | dirty )            cmd='dirty'
-                                ;;
-        -c | checkout )         cmd='checkout'
-                                break
-                                ;;                                
-        -h | help )             usage
-                                exit
-                                ;;
-        * )                     usage
-                                exit 1
-    esac
-    shift
+	case $1 in
+	-r | repos)
+		cmd='repos'
+		;;
+	-p | pull)
+		cmd='pull'
+		;;
+	-up | standup)
+		cmd='standup'
+		# consume arguments
+		while [ "$1" != "" ]; do
+			echo "param : $1"
+			#case $1 in
+			#esac
+			shift
+		done
+		;;
+	-s | status)
+		cmd='status'
+		;;
+	-f | fetch)
+		cmd='fetch'
+		;;
+	-df | diff)
+		cmd='diff'
+		;;
+	-b | branch)
+		cmd='branch'
+		shift
+		cmd_branch_extended=$1
+		;;
+	-l | log)
+		cmd='log'
+		;;
+	-d | dirty)
+		cmd='dirty'
+		;;
+	-c | checkout)
+		cmd='checkout'
+		break
+		;;
+	-h | help)
+		usage
+		exit
+		;;
+	*)
+		usage
+		exit 1
+		;;
+	esac
+	shift
 done
 
 # process repositories starting from the current directory as an anchor
 # Find toplevel git directories starting from current directory and going up N leveles
 
 start=$(pwd)
-while IFS= read -r -d $'\n' line; do 
-    cd "$line"
-    toplevel=$(git rev-parse --show-toplevel 2>/dev/null)        
-    if [ -n "$toplevel" ]; then
-        projects[$toplevel]=$toplevel
-        # Create random color associated with this project
-        pcolors[$toplevel]=$(($RANDOM * 256 / 32767 + 1))
+while IFS= read -r -d $'\n' line; do
+	cd "$line"
+	toplevel=$(git rev-parse --show-toplevel 2>/dev/null)
+	if [ -n "$toplevel" ]; then
+		projects[$toplevel]=$toplevel
+		# Create random color associated with this project
+		pcolors[$toplevel]=$(($RANDOM * 256 / 32767 + 1))
 
-        # create color based on check sum (using something less than 256 so we don't get too bright of the colors)
-        sum=$(cksum <<< $toplevel | cut -f 1 -d ' ')
-        pcolors[$toplevel]=$(($sum % 225))
-    fi
-done <<< $(find `pwd` -maxdepth 3 -type d)
+		# create color based on check sum (using something less than 256 so we don't get too bright of the colors)
+		sum=$(cksum <<<$toplevel | cut -f 1 -d ' ')
+		pcolors[$toplevel]=$(($sum % 225))
+	fi
+done <<<$(find $(pwd) -maxdepth 3 -type d)
 cd $start
 
-echo "Discovered :: ${#projects[@]}"
-echo "cmd :: ${cmd}"
+# echo "Discovered :: ${#projects[@]}"
+# echo "cmd :: ${cmd}"
 
 # Commands that can be handled at directory level
-for file in "${projects[@]}"; do     
-     # resolve symlinks
-     if [[ -d "$file" && ! -L "$file" ]]; then  
-        cd "$file"
+for file in "${projects[@]}"; do
+	# resolve symlinks
+	if [[ -d "$file" && ! -L "$file" ]]; then
+		cd "$file"
 
-        case ${cmd} in
-            ("repos")
-                        repo_repos
-                        ;;
-            ("pull")
-                        repo_pull
-                        ;;
-            ("status")
-                        repo_status
-                        ;;
+		case ${cmd} in
+		"repos")
+			repo_repos
+			;;
+		"pull")
+			repo_pull
+			;;
+		"status")
+			repo_status
+			;;
 
-            ("standup")
-                        repo_stanup
-                        ;;
-            ("branch")
-                        repo_branch
-                        ;;
-            ("log")
-                        repo_log
-                        ;;
-            ("dirty")
-                        repo_dirty
-                        ;;                 
-           ("fetch")
-                        repo_fetch
-                        ;;                                
-           ("diff")
-                        repo_diff                         
-        esac           
-    fi; 
-done   
+		"standup")
+			repo_stanup
+			;;
+		"branch")
+			repo_branch
+			;;
+		"log")
+			repo_log
+			;;
+		"dirty")
+			repo_dirty
+			;;
+		"fetch")
+			repo_fetch
+			;;
+		"diff")
+			repo_diff
+			;;
+		esac
+	fi
+done
 
 # echo 'Aggregated commands'
 case ${cmd} in
-    ("checkout")
-                repo_checkout "$@"
-                ;;                         
-esac   
+"checkout")
+	repo_checkout "$@"
+	;;
+esac
